name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    #- name: Install Dependencies
    #  run: composer require laravel/breeze --dev
    #- name: Install other dependencie
    #  run: php artisan breeze:install blade
    #  working-directory: microsites_ptp/artisan
    #- name: Generate key
    #  run: php artisan key:generate
    #  working-directory: microsites_ptp
    #- name: Directory Permissions
    #  run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.mysql
    #- name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
    #  env:
    #    DB_CONNECTION: mysql
    #    DB_DATABASE: database/database.mysql
    #  run: php artisan test

  push:
    runs-on: ubuntu-latest
    needs: laravel-tests  # Este paso depende del paso de construcción anterior
  
    steps:
    - name: Check if laravel-tests failed
      run: exit ${{ job.status }}  # Salir con el estado de la construcción actual
  
    - name: Push changes to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de acceso de GitHub